"""English UI strings."""

TEXTS = {
    "welcome_first": (
        "Welcome to <b>BASALT Casino</b>.\n\n"
        "Play dice, darts, basketball and more. Use demo mode to try without risk, "
        "or switch to real mode and deposit to play for real.\n\n"
        "Choose an action below."
    ),
    "welcome_return": "Welcome back to <b>BASALT Casino</b>. Choose an action below.",
    "main_menu_caption": "Main menu. Account — profile, stats, deposit. Play — choose a game.",
    "btn_account": "Account",
    "btn_play": "Play",
    "tech_works_global": "⛔ Technical works. Please try again later.",
    "tech_works_demo": "⛔ Demo mode is temporarily unavailable.",
    "tech_works_real": "⛔ Real mode is temporarily unavailable.",
    "block_full": "⛔ Access restricted. You can only view statistics.",
    "block_partial": "⛔ Switching to real mode and withdrawals are disabled for your account.",
    "account_caption": "Account: statistics, settings, mode, deposit, language.",
    "btn_stats": "Statistics",
    "btn_settings": "Settings",
    "btn_mode": "Mode",
    "btn_deposit": "Deposit",
    "btn_language": "Language",
    "btn_referral": "Become a referral",
    "btn_share": "Share referral link",
    "referral_caption": (
        "👥 <b>Referral Program</b>\n\n"
        "Share this link with friends. When they start the bot, both you and your friend get {bonus} ₽!\n\n"
        "Your link:\n<code>{link}</code>\n\n"
        "You can copy it or use the Share button below."
    ),
    "referral_share_text": "\nJoin me at BASALT Casino and get bonus!",
    "btn_back": "Back",
    "btn_exit": "Exit",
    "settings_caption": "Notifications and FAST MODE (show result immediately after throw).",
    "btn_notifications": "Notifications",
    "btn_fast_mode": "FAST MODE",
    "mode_caption_demo": "Current mode: <b>DEMO</b>. Virtual balance, no withdrawal. Switch to real mode to play for money.",
    "mode_caption_real": "Current mode: <b>Real</b>. Real balance, deposit and withdrawal available.",
    "btn_switch_to_real": "Switch to Real",
    "btn_switch_to_demo": "Switch to DEMO",
    "language_caption": "Select language / Выберите язык.",
    "btn_lang_ru": "RU",
    "btn_lang_en": "EN",
    "stats_caption": "View your statistics or reset display (data is kept).",
    "btn_stats_view": "📊 View statistics",
    "btn_stats_reset": "Reset statistics",
    "stats_reset_success": "Statistics reset (local only, data preserved in database)",
    "btn_stats_last10": "Last 10 games (WebApp)",
    "btn_stats_full": "Full statistics (WebApp)",
    "deposit_caption": ("💳 <b>Deposit & Withdrawal</b>\n" "Mode: {mode} | Balance: {balance}\n\n" "Rules: Choose amount and create a request. Admin will process it after payment."),
    "btn_topup": "Top up",
    "btn_send_contact": "Send contact",
    "contact_screen_caption": (
        "Contact is used for payment requests (deposit/withdraw). " "Your number is visible only to the administrator. This is done once — the button will disappear afterwards."
    ),
    "contact_btn_confirm": "Confirm",
    "contact_share_prompt": "Press the button below to share your contact with the bot.",
    "contact_saved": "Contact saved. The «Send contact» button will no longer appear.",
    "contact_required_for_request": "Please send your contact first (button «Send contact» in the deposit menu). You cannot create requests without it.",
    "deposit_amount_caption": "Select amount (min {min_bet} – max {max_bet} ₽) or enter your own.",
    "btn_custom_amount": "Custom amount",
    "btn_cancel": "Cancel",
    "deposit_create_caption": "Create a deposit request for <b>{amount} ₽</b>.",
    "btn_create_request": "Create request",
    "btn_i_paid": "I paid",
    "deposit_request_created": "Request #{request_id} for {amount} ₽ created. Admin will process after payment.",
    "deposit_custom_prompt": "Enter amount ({min_bet} – {max_bet} ₽):",
    "deposit_custom_invalid": "Invalid amount. Enter a number between {min_bet} and {max_bet}.",
    "notifications_on": "Notifications ✅",
    "notifications_off": "Notifications ❌",
    "fast_mode_on": "FAST MODE ✅",
    "fast_mode_off": "FAST MODE ❌",
    "games_list_caption": "Choose a game.",
    "game_description": "<b>{name}</b>\n\n<b>Possible outcomes:</b>\n{outcomes}",
    "game_name_1": "🎲 2 Dices",
    "game_name_2": "🎲 More/Less",
    "game_name_3": "🎲 Even/Odd",
    "game_name_4": "🎯 Darts",
    "game_name_5": "🏀 Basketball",
    "game_name_6": "⚽ Football",
    "game_name_7": "🎳 Bowling",
    "game_name_8": "🎰 Slots",
    "game_outcome_1_0": "Victory 1",
    "game_outcome_1_1": "Victory 2",
    "game_outcome_1_2": "Draw",
    "game_outcome_2_0": "More",
    "game_outcome_2_1": "Less",
    "game_outcome_3_0": "Even",
    "game_outcome_3_1": "Odd",
    "game_outcome_4_0": "Red",
    "game_outcome_4_1": "White",
    "game_outcome_4_2": "Center",
    "game_outcome_4_3": "Miss",
    "game_outcome_5_0": "Score",
    "game_outcome_5_1": "Miss",
    "game_outcome_5_2": "Stuck",
    "game_outcome_6_0": "Goal",
    "game_outcome_6_1": "Miss",
    "game_outcome_6_2": "Hit post",
    "game_outcome_6_3": "Goal off post",
    "game_outcome_6_4": "Clean goal",
    "game_outcome_6_5": "Crossbar goal",
    "game_outcome_7_0": "Miss",
    "game_outcome_7_1": "Strike",
    "game_outcome_7_2": "Hit 1-6",
    "game_outcome_7_3": "Hit 1-3",
    "game_outcome_7_4": "Hit 3-6",
    "game_outcome_8_0": "Grapes (3)",
    "game_outcome_8_1": "Lemons (3)",
    "game_outcome_8_2": "BAR BAR BAR",
    "game_outcome_8_3": "7-7-7",
    "game_make_bet": "Make bet",
    "game_choose_outcome": "Choose outcome:",
    "game_currency_note": "\n\nWhen entering a custom bet amount, you need to enter it in rubles (₽). All balance changes will be processed in Russian Rubles.",
    "game_choose_amount": "Your balance: {balance} {demo_note}{currency_note}\n\nChoose bet amount (will be deducted from balance):",
    "game_choose_amount_demo_note": " (DEMO account)",
    "confirm_bet_text": (
        "Game: <b>{game_name}</b>\n"
        "Outcome: <b>{outcome}</b>\n"
        "Bet: <b>{amount}</b>\n"
        "Coefficient: <b>{ratio}</b>\n"
        "Probability: <b>{prob:.0%}</b>\n"
        "Potential win: <b>{potential}</b>\n"
        "Current balance: <b>{current_balance}</b>\n"
        "Potential balance: <b>{potential_balance}</b>\n\n"
        "Confirm or change below."
    ),
    "btn_place_bet": "Place bet",
    "btn_change_amount": "Change amount",
    "btn_change_outcome": "Change outcome",
    "win_message": "🎉 You won! +{amount}",
    "lost_message": "😔 You lost. Try again!",
    "btn_repeat": "Repeat",
    "btn_choose_game": "Choose game",
    "game_bet_insufficient": "Insufficient balance. Top up or switch to demo.",
    "game_already_played": "This bet was already placed. Use the result menu.",
    "btn_restore_demo": "Restore demo balance",
    "demo_restore_success": "Demo balance has been restored. You can play again.",
    "next_restore_in": "Next restore available in {time_left}.",
    "demo_restore_not_needed": "Your demo balance is sufficient. No restore needed.",
    "btn_withdraw": "Withdraw",
    "withdraw_caption": "Withdraw funds to your account. Select amount and create a request. Admin will process it.",
    "withdraw_amount_caption": "Select amount to withdraw (min {min_bet} – max {max_bet} ₽) or enter your own.",
    "withdraw_create_caption": "Create a withdraw request for <b>{amount} ₽</b>. Admin will process after verification.",
    "withdraw_request_created": "Withdraw request #{request_id} created for {amount} ₽. Admin will process it.",
    "withdraw_demo_blocked": "Withdraw is only available in real mode. Switch from demo to real mode first.",
    "payment_status_caption": "Your payment requests:",
    "payment_status_item": "#{id} {request_type} {amount} ₽ — {status}",
    "payment_status_empty": "No payment requests yet.",
    "btn_my_requests": "My requests",
    "status_pending": "pending",
    "status_approved": "approved",
    "status_rejected": "rejected",
    "admin_btn_users": "Manage users",
    "admin_btn_settings": "Casino settings",
    "admin_btn_payments": "Payment requests",
    "admin_btn_stats": "Statistics",
    "admin_btn_broadcast": "Broadcast",
    "admin_btn_block": "Block user",
    "admin_btn_balance": "Change balance",
    "admin_btn_user_stats": "User stats",
    "admin_btn_confirm": "Confirm",
    "admin_block_full": "Block (full)",
    "admin_block_partial": "Block (partial)",
    "admin_block_unblock": "Unblock",
    "admin_balance_real": "Real balance",
    "admin_balance_demo": "Demo balance",
    "admin_btn_approve": "Approve",
    "admin_btn_reject": "Reject",
    "admin_panel_caption": "Admin panel. Choose an action.",
    "admin_search_prompt": "Send user ID or username to search:",
    "admin_user_not_found": "User not found.",
    "admin_user_caption": "User {user_id}\n@{username}\n{full_name}\nBlocked: {blocked}\nReal: {real}₽ Demo: {demo}₽",
    "admin_stats_caption": "Users: {users_count}\nGames: {games_count}\nTotal deposited: {total_deposited}₽\nTotal withdrawn: {total_withdrawn}₽\nPending requests: {pending_count}",
    "admin_broadcast_prompt": "Send the broadcast text (one message):",
    "admin_broadcast_done": "Broadcast sent to {count} users.",
    "admin_set_value": "Current {key} = {value}. Send new value:",
    "admin_set_ok": "Updated {key} to {value}.",
    "admin_payment_caption": "Request #{id}\nUser: {user_id}\nType: {request_type}\nAmount: {amount}₽\nCreated: {created_at}",
    "admin_no_pending": "No pending requests.",
    "admin_new_request_caption": (
        "New request #{request_id}<br>Type: {request_type}<br>Amount: {amount} ₽<br>" "User ID: {user_id}<br>Username: {username}<br>Phone: {phone}<br>Created: {created_at}"
    ),
    "admin_btn_read": "Read",
    "admin_btn_dismiss": "Close",
    "admin_btn_exit": "Exit",
    "info_caption": (
        "<b>BASALT Casino</b>\n\n"
        "• <b>Account</b> — profile, statistics, mode (demo/real), deposit, language.\n"
        "• <b>Play</b> — dice, darts, basketball, football, bowling, slots.\n"
        "• Demo mode: virtual balance, no withdrawal. Real mode: deposit and play for money.\n\n"
        "Use the links below for rules, deposit info and support."
    ),
    "help_caption": "Need help? Write to support using the button below (a message will be prepared for you).",
    "btn_close": "Close",
    "info_btn_rules": "Rules",
    "info_btn_rules_games": "Game rules",
    "info_btn_deposit": "Deposit",
    "info_btn_support": "Support",
    "info_btn_faq": "FAQ",
    "help_btn_write": "Write to support",
    "help_start_text": "Hello, I need help with BASALT Casino.",
    "withdraw_insufficient_balance": "Insufficient balance for withdrawal.",
    "referrer_notification": "🎉 Great news! User {username} just registered using your referral link and you received a bonus!",
}
